spring:
  profiles:
    default: local #로컬 환경
  datasource:
    url: jdbc:mysql://localhost:3306/mydb  #mydb 데이터 베이스 사용
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver #DB 접속을 위한 Driver
  jpa:
    hibernate:
      ddl-auto: update #스키마 자동 업데이트
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.cache: trace #Redis 사용에 대한 로그가 조회되도록 설정

---

spring:
  config:
    activate:
      on-profile: prod #원격 환경
  datasource:
    url: jdbc:mysql://instagram-db.cvqk8wwquqiy.ap-northeast-2.rds.amazonaws.com:3306/mydb  #AWS RDS 사용
    username: admin
    password: password
  data:
    redis:
      host: instagram-cache-server.vzvxyg.ng.0001.apn2.cache.amazonaws.com
      port: 6379